name: Build Stencil Theme

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Stencil theme
        run: stencil bundle

      - name: Create archive
        uses: actions/upload-artifact@v2
        with:
          name: stencil-bundle
          path: public/dist/*.zip
