# Deploy Theme to Store when new changes are pushed to master branch
name: Deploy Theme to Store

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    # Move the generated zip file to the root directory
    - name: Move zip file to root directory
      run: pwd

   
