name: Deploy Stencil Theme to Store

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ develop ]  # Trigger on pushes to the develop branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]  # Test across multiple Node.js versions (optional)

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Install Stencil CLI Dependency
        run: npm install -g @bigcommerce/stencil-cli

      - name: Install Dependencies
        run: npm ci

      - name: Connect to Store (Avoid hardcoding secrets)
        # Use dedicated job for authentication to avoid exposing secrets in build logs
        uses: ./authenticate-store.yml  # Reference a separate workflow file

      - name: Build Stencil theme
        run: stencil bundle

      - name: Create archive
        uses: actions/upload-artifact@v2
        with:
          name: stencil-bundle
          path: public/dist/*.zip

  deploy-to-store:
    runs-on: ubuntu-latest  # Consider using the same runner for efficiency
    needs: build-and-upload  # Wait for the build job to complete

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: stencil-bundle

      - name: Push Stencil theme (Avoid hardcoding secrets)
        # Use dedicated job for authentication to avoid exposing secrets in build logs
        uses: ./authenticate-store.yml  # Reference the same authentication workflow
        env:
          # Provide environment variables for deployment within the authentication job
          ARTIFACT_PATH: ${{ runner.temp_dir }}/stencil-bundle.zip  # Download location

