name: Deploy Stencil Theme to Store

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ testflow ]  # Trigger on pushes to the develop branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]  # Test across multiple Node.js versions (optional)

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Install Stencil CLI Dependency (optional, if not already installed)
        run: npm install -g @bigcommerce/stencil-cli

      - name: Install Dependencies
        run: npm ci

      # Remove this step if building is not done here
      #- name: Build Stencil theme (assuming pre-built zip exists)
      #  # No bundling step here, assuming the zip is already available

      # Add a check for pre-built zip and upload conditionally (optional)
      - name: Upload pre-built zip (if exists)
        run: |
          if [[ -f public/dist/*.zip ]]; then
            echo "Uploading pre-built zip..."
            uses: actions/upload-artifact@v2
            with:
              name: stencil-bundle
              path: public/dist/*.zip
          fi
        shell: bash

  deploy-to-store:
    runs-on: ubuntu-latest  # Consider using the same runner for efficiency
    needs: build-and-upload  # Wait for the build job to complete (optional)

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact (if building in first job)
        uses: actions/download-artifact@v2
        with:
          name: stencil-bundle  # Optional, if building in first job
          path: ${{ runner.temp_dir }}/stencil-bundle.zip  # Optional, if building in first job

      - name: Push theme live, automatically deleting oldest theme if necessary
        # Assuming the zip file is downloaded in the previous step (if building in first job)
        run: stencil push -a -d -c 1
          ${{ runner.temp_dir }}/stencil-bundle.zip  # Download location (if building in first job)
